### ISSUE TITLE
大哥，有没有恢复微软雅黑的脚本

### ISSUE THREAD

**Issue by ghost** [Moeologist/font-hack#1]

**Comment by ghost** [comment]
msyh-backup already exist!
Downloading sarasa fonts...
拒绝访问。
拒绝访问。
子目录或文件 bin.7z 已经存在。
系统找不到指定的路径。
Download failed!
Custom font not generated!
Press any key to logout
请按任意键继续. . .
这不知道啥情况

**Comment by Moeologist** [comment]
看起来像下载sarasa字体和7zip失败了，这两个下载都会被GFW墙住，这种情况应该没有动设置，忽视吧
